version: '3.4'

services:
  serviciotienda.api.autor:
    image: ${DOCKER_REGISTRY-}serviciotiendaapiautor
    build:
      context: .
      dockerfile: ServicioTienda.Api.Autor/Dockerfile
  serviciotienda.api.libro:
    image: ${DOCKER_REGISTRY-}serviciotiendaapilibro
    build:
      context: .
      dockerfile: ServicioTienda.Api.Libro/Dockerfile

  serviciotienda.api.carritocompra:
    image: ${DOCKER_REGISTRY-}serviciotiendaapicarritocompra
    build:
      context: .
      dockerfile: ServicioTienda.Api.CarritoCompra/Dockerfile

  serviciotienda.api.gateway:
    image: ${DOCKER_REGISTRY-}serviciotiendaapigateway
    build:
      context: .
      dockerfile: ServicioTienda.Api.Gateway/Dockerfile

networks:
  default:
    external:
        name: redmicroservicio


