version: '3.4'

services:
  serviciotienda.api.autor:
    image: ${DOCKER_REGISTRY-}serviciotiendaapiautor
    build:
      context: .
      dockerfile: ServicioTienda.Api.Autor/Dockerfile
  serviciotienda.api.libro:
    image: ${DOCKER_REGISTRY-}serviciotiendaapilibro
    build:
      context: .
      dockerfile: ServicioTienda.Api.Libro/Dockerfile

networks:
  default:
    external:
        name: redmicroservicio
